# Generated by Django 5.1.6 on 2025-02-18 12:04

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('743d64c5-9f7d-4664-937c-c7644fdaee34'), primary_key=True, serialize=False, unique=True),
        ),
    ]
